# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Vanilla Digital Studio
email: sandrine.zecler@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Mon laboratoire d'idées.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: szecler
github_username:  vanillads
# Mailing list signup form
signup_form_url: http://eepurl.com/c2rTVz

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

assets:
  sources:
    - bower_components/foundation-sites/scss
    - _assets/css
    - bower_components/foundation-sites/dist/js
    - bower_components/jquery/dist
    - bower_components/what-input/dist
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE >= 9"
      - "and_chr >= 2.3"

collections:
  my_categories:
    output: true
    permalink: /collections/:name/
  my_tags:
    output: true
    permalink: /tags/:name/

defaults:
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:title/

# Due to us using the categories for posts then it is advisable to explicitly specify a
# permalink structure for the site. Otherwise Jekyll attempts to organize the pages in folders
# by the category names and it doesn't understand multi-categories to well :/
permalink: none

# Pagination Settings
pagination:
  enabled: true
  per_page: 6
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
